### ISSUE TITLE
MSE Cross-validation

### ISSUE THREAD

**Issue by ecikanek** [skorsu/Stats506_Project#15]
For the cross-validation, based on the plots the number of knots does not seem to match the lowest MSE. Perhaps I am misreading something?

**Comment by ecikanek** [comment]
@skorsu sorry I meant to tag you in the original post!

**Comment by skorsu** [comment]
I will check it now!

**Comment by skorsu** [comment]
Nice catch, @ecikanek. Thanks! I have edited the code for the number of knot. Here is what I got.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/71246225/100155408-39296e80-2e75-11eb-8479-bdd1e0f52263.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/71246225/100155433-45153080-2e75-11eb-9419-af45c3f84c72.png">

Seems like there is no changes in the Natural Spline; however, I have made some mistakes in the basis spline. Right now, I will use 1 knot for `basis` and 4 knots for `natural` spline.

**Comment by ecikanek** [comment]
@skorsu great! I am looking to see how easy it might be for me to also do the MSE cross validation for my basis and natural spline - so the code is consistent. I would like to keep this ticket open so I can update it a little later. 👍

**Comment by skorsu** [comment]
I have an error during fitting the spline, both of my models contain NA. Did you guys get something like this? @ecikanek @kylewschulz 

`Basis Spline`
<img width="798" alt="image" src="https://user-images.githubusercontent.com/71246225/100156388-c9b47e80-2e76-11eb-96c9-146c967d6db2.png">

`Natural Spline`
<img width="798" alt="image" src="https://user-images.githubusercontent.com/71246225/100156353-bb666280-2e76-11eb-8f28-c99ac85b946d.png">

**Comment by kylewschulz** [comment]
Interesting - I will look into this right now. Separate note, is there a reason you're using education factor in the natural spline and edu continuous in the basis spline? @skorsu

**Comment by ecikanek** [comment]
@skorsu I am updating my code now and will check back when I'm done - I currently don't have NAs though, but when I update this might change?

**Comment by skorsu** [comment]
@kylewschulz Oh, my mistake. I suppose to use `edu` for both model. Thanks!

Thanks, @ecikanek

**Comment by skorsu** [comment]
I have solved the problem! I have fit the spline by using the `df` instead of the `number of knots`.

> **Cubic Spline (Basis/Natural)**
Basis Spline: df = 4 + knots
Natural Spline: df = 2 + knots

For the MSE plot, the natural spline gives the similar result for both methods. (`knots` and `df`) However, for the basis spline, the plot look slightly different when the `df` = 5 and 6 (or `number of knots` = 1 and 2).

<img width="664" alt="Screen Shot 2563-11-24 at 17 27 39" src="https://user-images.githubusercontent.com/71246225/100158578-63c9f600-2e7a-11eb-98cd-dc149e84c26e.png">

The MSE is nearly the same. So, I think that we can use any of them. What do you think? @ecikanek @kylewschulz

**Comment by kylewschulz** [comment]
I'm fine with what we have right now, it looks like 6 is technically the minimum, so we can note that as a reason for why we chose what we did @ecikanek @skorsu

**Comment by ecikanek** [comment]
So the cross-validation in stata is...not great? I am going to keep working on it but @kylewschulz do you have cross validation in your python code?

**Comment by kylewschulz** [comment]
@ecikanek sorry just saw this, I actually was planning on just writing a section about cross validation and mentioning that it was executed in r and that python doesn't have a natural implementation for this feature

**Comment by kylewschulz** [comment]
Looks like this has been resolved
