### ISSUE TITLE
Stepwise Regression Cuts

### ISSUE THREAD

**Issue by kylewschulz** [skorsu/Stats506_Project#17]
Hey @skorsu @ecikanek,

I believe I remembered we were going to set 5 cut points into 6 regions for the stepwise regression and wanted to double check, I noticed Keven had 4 into 3 and Erin had 5 into 6, just wanted to make sure these match

**Comment by skorsu** [comment]
I have edited the R to be the same as Stata. Thanks! @kylewschulz
