### ISSUE TITLE
Core Analysis Organization

### ISSUE THREAD

**Issue by skorsu** [skorsu/Stats506_Project#19]
Hi! @kylewschulz @ecikanek 

I just want to confirm the organization of the core analysis part. Since the Piecewise Regression seems to be different from the Polynomial Regression and Splines, should we start with Piecewise then Polynomial and Splines? So, I can organize the method part too.

Thanks!

**Comment by ecikanek** [comment]
I am indifferent to this - but thought the way it was organized was in a way as to what a person might try first if they realized a non-linear fit was best. So they would likely do a polynomial fit first and then piecewise and then the splines. 

But again happy to change to whatever seems best.

**Comment by skorsu** [comment]
Right now, I think both R and Stata part has a similar organization. which are
- Linear Regression
- Polynomial Regression
- Piecewise
- Spline

So I think we can keep this organization. :)

**Comment by kylewschulz** [comment]
I can confirm I have matched my code to match up with this organization. 

Thanks for the guide - closing this issue !
