### ISSUE TITLE
Coding of Education 

### ISSUE THREAD

**Issue by kylewschulz** [skorsu/Stats506_Project#2]
I notice we currently have a mismatch - the R script treats education as a dummy variable whereas the stata code treats it as a 1-5 ordinal variable. Do we know which version we want to use in the final example?

**Comment by skorsu** [comment]
I have edited the R part. I treated the education variable as an ordinal variable, the same as in the STATA part.

**Comment by ecikanek** [comment]
Since this appears resolved I'm going to close this issue.
