### ISSUE TITLE
Natural Cubic Spline - code variation

### ISSUE THREAD

**Issue by ecikanek** [skorsu/Stats506_Project#22]
Hi All, 

For my natural spline, stata allows me to create the points for the knots or just specify the number of knots. I've included the code used for each of the regressions: one I specify the locations of the knots (mkspline age_nc=age, cubic knots(18 35 50 65 80)

the other I let the program pick the location of the knots and just specify the number (mkspline age_nspk=age, cubic nknots(6)) 

Let me know what you think. My regression here does not match in the number of variables as @skorsu's but again, this might just be a program issue and something to explain in the tutorial.  

<img width="668" alt="Screen Shot 2020-11-24 at 11 11 50 PM" src="https://user-images.githubusercontent.com/14208044/100182378-70fed900-2eaa-11eb-97ab-1d150c9693d5.png">

<img width="680" alt="Screen Shot 2020-11-24 at 11 10 58 PM" src="https://user-images.githubusercontent.com/14208044/100182321-50cf1a00-2eaa-11eb-9f3e-ef32d4bf45ea.png">

**Comment by skorsu** [comment]
I think your R^2 is quite similar to the R^2 from Python and R. I don't think it will be any problem. We can put it in the discussion.
